# Builder Stage
FROM oven/bun:1 as builder
RUN apt-get update -y && apt-get install -y openssl
RUN bun add -g turbo
WORKDIR /app
COPY package.json bun.lock turbo.json ./
COPY apps/socket/package.json ./apps/socket/
COPY apps/web/package.json ./apps/web/
COPY apps/wserver/package.json ./apps/wserver/
COPY packages/db/package.json ./packages/db/
COPY packages/db/schema.prisma ./packages/db/
COPY packages/redis/package.json ./packages/redis/
COPY packages/types/package.json ./packages/types/
COPY packages/typescript-config/package.json ./packages/typescript-config/
RUN bun install --frozen-lockfile
COPY . .
RUN turbo run build

# Runner Stage
FROM node:20-slim as runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/apps/web/package.json ./apps/web/
COPY --from=builder /app/apps/web/.next ./apps/web/.next
COPY --from=builder /app/apps/socket/dist ./apps/socket/dist
COPY --from=builder /app/apps/wserver/dist ./apps/wserver/dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
EXPOSE 3000 3001
CMD ["./start.sh"]
