# .github/workflows/ci.yml

name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Linting on Affected Workspaces
        run: pnpm turbo run lint --filter="...[origin/main]"

      - name: Run Tests on Affected Workspaces
        run: pnpm turbo run test --filter="...[origin/main]"

      - name: Run Builds on Affected Workspaces
        run: pnpm turbo run build --filter="...[origin/main]"